### ISSUE TITLE
ConsoleView & ProcessPipe usage outside of SwiftUI Previews?

### ISSUE THREAD

**Issue by IgorMuzyka** [insidegui/MacPreviewUtils#1]
Hi, this is a question, not an issue.

I borrowed the `ConsoleView` & `ProcessPipe` to use in `SwiftUI` macOS App which i run with `swift run ...` for debug purposes.

`ConsoleSearchFiled` obviously not working in this setup, because keyboard is captured by the terminal, not the process, but thats just a note not of any importance.

`ProcessPipe` though has the following code in `read` method:
```swift
if !ProcessInfo.isSwiftUIPreview {
    assertionFailure("\(source) streaming failed: \(error)")
}
```
It naturally got overwritten with `print(error)` which i guess is a bad idea.

At some point I noticed that if i `print(...)` something with **multiple lines** it *sometimes* gets **corrupted** on the receiving side.

I understand this wasn't designed for how i use it at all.

My question is what changes would you suggest to get rid of that multiline string **corruption** issue?
I suppose it has to do with how we `read` the `Pipe`.
A nudge in the right direction would be much appreciated.

**Comment by IgorMuzyka** [comment]
Here's an example of corruption:
<img width="1012" alt="screenshot 2023-08-26 at 23 27 38" src="https://github.com/insidegui/MacPreviewUtils/assets/4402333/efb78b1d-f215-460d-bc0a-d1b6207298e8">
While the actual `JSON` looks like this:
```json
{
  "event" : {
    "__preserved_type" : "KeyboardEvent.Type",
    "__type_preserving_strategy" : 0,
    "value" : "keystroke"
  },
  "object" : {
    "__preserved_type" : "KeyBehaviorDescriptor.Type",
    "__type_preserving_strategy" : 0,
    "keyStroke" : {
      "_0" : [
        {
          "control" : {
            "_0" : "⌘"
          }
        },
        {
          "control" : {
            "_0" : "⇧"
          }
        },
        {
          "letter" : {
            "_0" : "y"
          }
        }
      ],
      "targetApplication" : {
        "byName" : {
          "_0" : "Xcode"
        }
      }
    }
  },
  "sender" : "iphone.local"
}
```

**Comment by IgorMuzyka** [comment]
Tried reducing timeout in `try? await Task.sleep(nanoseconds: 1_000_000)` in `ConsolView` - no difference.
But disabling `autoscroll` helps to some degree, still some lines are just missing.

**Comment by insidegui** [comment]
It's hard to know for sure without seeing all of the code, but it looks like there's additional output being sent to stdout other than the streamed JSON data. If you can share what you have in a repo with reproduction steps I'd be happy to take a look.

**Comment by IgorMuzyka** [comment]
@insidegui here's a repo with [example](https://github.com/IgorMuzyka/ConsoleViewCorruption).

**Comment by insidegui** [comment]
@IgorMuzyka 

~Looking at the repo and testing it here, I believe the issue is that you're trying to adapt a system that was made to work with `os_log` (or `Logger`) messages to work with vanilla stdout (`print`).~

~The reason MacPreviewUtil's implementation gets messages in JSON format is because it's using the `log stream` command under the hood to stream console messages with `--style ndjson`, in which case the `log` command will output a single JSON object per line, so using `pipe.fileHandleForReading.bytes.lines` works perfectly.~

~If you're trying to handle streams with multiple lines where you need to collect them in order to form a complete message, you'll have to implement custom handling for that.~

Forget that, I was confusing this with something similar I've implemented in VirtualBuddy, but MacPreviewUtils is not using `log stream`.

**Comment by IgorMuzyka** [comment]
@insidegui worked around this issue.
I ended up suspecting that problem must have originated from `await MainActor.run` and `try? await Task.sleep(nanoseconds: 1_000_000)` so worked around that.
Some context: i also use [SwiftShell](https://github.com/kareman/SwiftShell) in that project, so i glanced on how their `onOutput` for `ReadableStream` works.
~~Currently i broke autoscroll, but not that it's really important to me.~~
Autoscroll just needed `DispatchQueue.main.asyncAfter(deadline: .now() + 1)`.
The upside is messages now aren't corrupting whatever their size/length. Another upside is that when `ConsoleView` disappears from view hierarchy we don't lose the messages with it.
This is just FYI.

Here is the solution i ended up with:
```swift 
final class ProcessPipeV2: ObservableObject {
    public static let shared = ProcessPipeV2()
    private let pipe: Pipe
    /// now just observing this
    @Published private(set) public var messages = [ProcessPipe.Message]()
    /// for autoscroll to capture new message event like:
    /// `.onReceive(processPipe.newMessage.eraseToAnyPublisher()) { message in`
    public let newMessage = PassthroughSubject<ProcessPipe.Message, Never>()

    private init() {
        self.pipe = Pipe()
        setvbuf(Darwin.stdout, nil, _IOLBF, 0)
        dup2(pipe.fileHandleForWriting.fileDescriptor, STDOUT_FILENO)

        pipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData

            guard let string = String(data: data, encoding: .utf8) else {
                fatalError("failed to read string, probably wrong encoding")
            }
            let message = ProcessPipe.Message(source: .stdout, contents: string)

            DispatchQueue.main.async { [unowned self] in
                messages.append(message)
                newMessage.send(message)
            }
        }
    }
}
```

The `ConsoleView` receives this as `@EnvironmentObject var processPipe: ProcessPipeV2`, and then we just use `processPipe.messages` in `filteredMessages`.
